### ISSUE TITLE
Optimization with repartition on assign throws exception

### ISSUE THREAD

**Issue by noreentry** [dask/dask-expr#1118]
optimization with FuseIO throws an exception

```python
import dask.dataframe as dd

path1 = '/foo/some-parq-with-index'
df1 = dd.read_parquet(path1, calculate_divisions=True)
print(df1.index)  # <dask_expr.expr.Index: expr=Index(frame=ReadParquetFSSpec(64d29fe))>
print(df1.columns)  # Index(['val1', 'val2', 'val3', 'val4', 'val5', 'val6', 'val7', 'tsprv'], dtype='object')
print(len(df1.divisions))  # 201

df1 = df1.assign(dts=df1.index - df1.tsprv)
print(df1.dts.min().compute())
```

**exception**

```
Traceback (most recent call last):
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/foo/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/foo/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/foo/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/foo/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/foo/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "prjs/dbg-dask/dbg-autopart.py", line 25, in <module>
    print(df1.dts.min().compute())
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_collection.py", line 476, in compute
    out = out.optimize(fuse=fuse)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_collection.py", line 591, in optimize
    return new_collection(self.expr.optimize(fuse=fuse))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 94, in optimize
    return optimize(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 3066, in optimize
    return optimize_until(expr, stage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 3037, in optimize_until
    expr = optimize_blockwise_fusion(expr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 3235, in optimize_blockwise_fusion
    expr, done = _fusion_pass(expr)
                 ^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 3200, in _fusion_pass
    dep.npartitions == root.npartitions or next._broadcast_dep(dep)
    ^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 398, in npartitions
    return len(self.divisions) - 1
               ^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 382, in divisions
    return tuple(self._divisions())
                 ^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 2074, in _divisions
    return super()._divisions()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 529, in _divisions
    if not self._broadcast_dep(arg):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 520, in _broadcast_dep
    return dep.npartitions == 1 and dep.ndim < self.ndim
           ^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 398, in npartitions
    return len(self.divisions) - 1
               ^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 382, in divisions
    return tuple(self._divisions())
                 ^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 529, in _divisions
    if not self._broadcast_dep(arg):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 520, in _broadcast_dep
    return dep.npartitions == 1 and dep.ndim < self.ndim
           ^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 398, in npartitions
    return len(self.divisions) - 1
               ^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 382, in divisions
    return tuple(self._divisions())
                 ^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 2629, in _divisions
    return super()._divisions()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/miniconda3/envs/py312forge/lib/python3.12/site-packages/dask_expr/_expr.py", line 533, in _divisions
    assert arg.divisions == dependencies[0].divisions
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

```
# _expr.py:530 class Blockwise(Expr)._divisions(self):
print(len(arg.divisions), len(dependencies[0].divisions))  # 26 15
print(self)  # Index(frame=FusedIO(d23609f)) - FusedIO(7aa0726)['tsprv']
```

**Environment**:
```
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0] on linux

dask                                2024.8.0-pyhd8ed1ab_0
dask-core                           2024.8.0-pyhd8ed1ab_0
dask-expr                              1.1.10-pyhd8ed1ab_0
```

P.S. is it possible to disable all these optimization? need stable prod, not 'smart-but-buggy'

**Comment by phofl** [comment]
Hi, thanks for your report. No you can't disable the optimiser, parts of it need to run to get something that you can execute. 

Can you provide a proper reproducer? When I use a parquet file with an index, this works and does raise. Please add a code snippet that creates a parquet file that triggers this error

**Comment by noreentry** [comment]
My dataset is very big and proprietary - so I'll try to recreate it with the same params (divisions, num of columns and so on).
But what I've found atm: for the expression (df.Index - df.tsprv) there are two rewrites with FusedIO - one with operand("columns") = [tsprv], so _fusion_compression_factor ~ 1/8 and the second one (reading index) with "columns" = [] (!empty, not None), so _fusion_compression_factor = 0.001 (should be 1?)
And
io/io.py:141
```
        step = math.ceil(1 / self.operand("_expr")._fusion_compression_factor)
        step = min(step, math.ceil(math.sqrt(npartitions)), 100)

        buckets = [partitions[i : i + step] for i in range(0, npartitions, step)]
        return buckets
```
gives different step and not correlated buckets for these two FusionIO

**Comment by noreentry** [comment]
no persist() and yes - df1 is the same for both objs

also if i do
```
df1 = dd.read_parquet(path1, calculate_divisions=True)
df1 = df1.reset_index().set_index('ts')  # index name is ts
```
everything is fine and no assertion error

**Comment by phofl** [comment]
Hm this is very odd. I am definitely curious what's going on here, I tried a bit more to come up with a reproducer but I couldn't find something that would raise.

**Comment by noreentry** [comment]
here is a reproducer
```
path1 = '/tmp/dbg1'
df1 = dd.from_array(np.zeros((201 * 10, 8), dtype=np.int64), columns=['val1', 'val2', 'val3', 'val4', 'val5', 'val6', 'val7', 'tsprv'])
df1.repartition(npartitions=201).to_parquet(path1, write_index=False)
# print(df1.head())

df1 = dd.read_parquet(path1, calculate_divisions=True)
df1 = df1.assign(dts=df1.index - df1.tsprv)
print(df1.dts.min().compute())
```

**Comment by phofl** [comment]
Thank you!

This one was nasty, I put up a PR to fix this, will be in the release later this week
